Feature/improve projects page og image
bestofjs/bestofjs pull request #233
Opened 2023-10-27 03:23 UTC by michaelrambeau

## Goal

- Improve the OG image for the `/projects` paths (introduced by #215 ) by showing the current sort option
- Add the current sort to page metadata, so that it shows up in the text displayed with the image on social networks

## How to test

## Screenshots

2023-10-27 09:55 UTC, zawarudo requested changes
Looks good so far, just need to fix the caching issue for OG images.

2023-10-27 10:05 UTC, michaelrambeau commented
> Looks good so far, just need to fix the caching issue for OG images.

Trying to kill the cache following the approach we did here: #229 

![image](https://github.com/bestofjs/bestofjs/assets/5546996/1f1ddb36-e840-4b0e-9f53-ee219ef3cd84)

2023-10-28 06:01 UTC, Evomatic approved these changes

2023-10-28 10:14 UTC, michaelrambeau commented
## `/api/stats` end-point

To understand better the cacheing issues, I'm adding an end-point to check if JSON data is stale.
By default, Next.js caches the result of `fetch` requests for ever.
The backend is supposed to trigger a revalidatation just after new data is made available.

Example of response:

```json
{
  "lastUpdateDate": "2023-10-27T21:20:19.029Z",
  "total": 1936,
  "relativeTime": "11.6 hours ago"
}
```

2023-10-28 10:41 UTC, michaelrambeau commented
## Screenshots

### Last 24 hours

<img width="675" alt="image" src="https://github.com/bestofjs/bestofjs/assets/5546996/64a9f33d-3144-40f9-a264-415e3bd17998">

### Last week

To be consistent with the HTML pages, I show the average numbers + N / day instead of the raw numbers.

![image](https://github.com/bestofjs/bestofjs/assets/5546996/cb628af4-402c-44a8-a5ca-c4a435629038)

2023-10-28 10:50 UTC, zawarudo approved these changes
LGTM

2023-10-28 10:52 UTC, merged